### ISSUE TITLE
Bot Appears Offline

### ISSUE THREAD

**Issue by Mrgibs** [robinuniverse/SvoxBot#1]
Hi, 

I set up the bot the way it shows in the video you made and the one you linked, however it appears as offline. I looked in the log file and there appears to be some issues happening.

Ive attached the log file.
[log.txt](https://github.com/Evshaddock/SvoxBot/files/2420260/log.txt)

Thanks.

**Comment by daisyUniverse** [comment]
Are you using Windows 7 or lower by chance?
This is actually news to me but it appears the Discord.NET API doesn't support Windows 7 and below very well and it's throwing errors indicating that

**Comment by daisyUniverse** [comment]
as for the specific reason why Windows 7 isn't supported, you can find it [here](https://github.com/RogueException/Discord.Net/issues/3), unfortunately it isn't really something I can personally fix

**Comment by Mrgibs** [comment]
Ah okay. Yes I am using windows 7, thats unfortunate. Thanks for the quick reply!
